CREATE DATABASE discord_translator_bot;
USE discord_translator_bot;
CREATE TABLE messages (bunch_id INT,chl_id BIGINT UNSIGNED, msg_id BIGINT UNSIGNED, lang CHAR(2), original BOOLEAN, expiration DATE);
CREATE TABLE channels (bunch_id INT,chl_id BIGINT UNSIGNED,lang CHAR(2));
SET GLOBAL event_scheduler=ON;
CREATE EVENT clean_messages_table ON SCHEDULE EVERY 1 DAY DO DELETE FROM messages WHERE expiration < CURRENT_DATE();
CREATE USER 'discord-translator-bot'@'localhost' IDENTIFIED BY 'password';
GRANT INSERT ON discord_translator_bot.messages TO 'discord-translator-bot'@'localhost';
GRANT SELECT ON discord_translator_bot.messages TO 'discord-translator-bot'@'localhost';
Flush Privileges;