CREATE DATABASE discord_translator_bot;
USE discord_translator_bot;
CREATE TABLE messages (bunch_id SMALLINT UNSIGNED,chl_id BIGINT UNSIGNED, msg_id BIGINT UNSIGNED, lang CHAR(2), original BIT, expiration DATE);
CREATE TABLE channels (bunch_id TINYINT UNSIGNED,chl_id BIGINT UNSIGNED,lang CHAR(2));
CREATE TABLE taskbuffer (task_id TINYINT, IDENTIFIER_1 BIGINT, IDENTIFIED_2 BIGINT);
SET GLOBAL event_scheduler=ON;
CREATE EVENT clean_messages_table ON SCHEDULE EVERY 1 DAY DO DELETE FROM messages WHERE expiration < CURRENT_DATE();
CREATE USER 'discord-translator-bot'@'localhost' IDENTIFIED BY 'password';
GRANT ALL ON discord_translator_bot TO 'discord-translator-bot'@'localhost';
Flush Privileges;